-- ============================================
-- PROCEDIMIENTOS PARTE 1 - FARMA
-- CRUD BASICO DE USUARIO, PACIENTE, MEDICO, MEDICAMENTO
-- ============================================

-------------------------------------------------
-- USUARIO
-------------------------------------------------

-- 1. Insertar usuario.
CREATE OR REPLACE PROCEDURE SP_INSERTAR_USUARIO (
    P_ID_ROL         IN NUMBER,
    P_CEDULA         IN VARCHAR2,
    P_NOMBRE         IN VARCHAR2,
    P_APELLIDO1      IN VARCHAR2,
    P_APELLIDO2      IN VARCHAR2,
    P_CORREO         IN VARCHAR2,
    P_USERNAME       IN VARCHAR2,
    P_CLAVE          IN VARCHAR2,
    P_ESTADO         IN VARCHAR2
)
AS
BEGIN
    INSERT INTO USUARIO (
        ID_ROL, CEDULA, NOMBRE, APELLIDO1, APELLIDO2, CORREO, USERNAME, CLAVE, ESTADO
    ) VALUES (
        P_ID_ROL, P_CEDULA, P_NOMBRE, P_APELLIDO1, P_APELLIDO2, P_CORREO, P_USERNAME, P_CLAVE, P_ESTADO
    );
END;
/

-- 2. Consultar usuario por ID.
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_USUARIO (
    P_ID_USUARIO IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM USUARIO
        WHERE ID_USUARIO = P_ID_USUARIO;
END;
/

-- 3. Actualizar usuario.
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_USUARIO (
    P_ID_USUARIO     IN NUMBER,
    P_ID_ROL         IN NUMBER,
    P_NOMBRE         IN VARCHAR2,
    P_APELLIDO1      IN VARCHAR2,
    P_APELLIDO2      IN VARCHAR2,
    P_CORREO         IN VARCHAR2,
    P_USERNAME       IN VARCHAR2,
    P_CLAVE          IN VARCHAR2,
    P_ESTADO         IN VARCHAR2
)
AS
BEGIN
    UPDATE USUARIO
    SET ID_ROL = P_ID_ROL,
        NOMBRE = P_NOMBRE,
        APELLIDO1 = P_APELLIDO1,
        APELLIDO2 = P_APELLIDO2,
        CORREO = P_CORREO,
        USERNAME = P_USERNAME,
        CLAVE = P_CLAVE,
        ESTADO = P_ESTADO
    WHERE ID_USUARIO = P_ID_USUARIO;
END;
/

-- 4. Desactivar usuario.
CREATE OR REPLACE PROCEDURE SP_DESACTIVAR_USUARIO (
    P_ID_USUARIO IN NUMBER
)
AS
BEGIN
    UPDATE USUARIO
    SET ESTADO = 'INACTIVO'
    WHERE ID_USUARIO = P_ID_USUARIO;
END;
/

-------------------------------------------------
-- PACIENTE
-------------------------------------------------

-- 5. Insertar paciente.
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PACIENTE (
    P_CEDULA     IN VARCHAR2,
    P_NOMBRE     IN VARCHAR2,
    P_APELLIDO1  IN VARCHAR2,
    P_APELLIDO2  IN VARCHAR2,
    P_TELEFONO   IN VARCHAR2,
    P_CORREO     IN VARCHAR2,
    P_ESTADO     IN VARCHAR2
)
AS
BEGIN
    INSERT INTO PACIENTE (
        CEDULA, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, CORREO, ESTADO
    ) VALUES (
        P_CEDULA, P_NOMBRE, P_APELLIDO1, P_APELLIDO2, P_TELEFONO, P_CORREO, P_ESTADO
    );
END;
/

-- 6. Consultar paciente por ID.
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_PACIENTE (
    P_ID_PACIENTE IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM PACIENTE
        WHERE ID_PACIENTE = P_ID_PACIENTE;
END;
/

-- 7. Actualizar paciente.
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PACIENTE (
    P_ID_PACIENTE IN NUMBER,
    P_NOMBRE      IN VARCHAR2,
    P_APELLIDO1   IN VARCHAR2,
    P_APELLIDO2   IN VARCHAR2,
    P_TELEFONO    IN VARCHAR2,
    P_CORREO      IN VARCHAR2,
    P_ESTADO      IN VARCHAR2
)
AS
BEGIN
    UPDATE PACIENTE
    SET NOMBRE = P_NOMBRE,
        APELLIDO1 = P_APELLIDO1,
        APELLIDO2 = P_APELLIDO2,
        TELEFONO = P_TELEFONO,
        CORREO = P_CORREO,
        ESTADO = P_ESTADO
    WHERE ID_PACIENTE = P_ID_PACIENTE;
END;
/

-- 8. Desactivar paciente.
CREATE OR REPLACE PROCEDURE SP_DESACTIVAR_PACIENTE (
    P_ID_PACIENTE IN NUMBER
)
AS
BEGIN
    UPDATE PACIENTE
    SET ESTADO = 'INACTIVO'
    WHERE ID_PACIENTE = P_ID_PACIENTE;
END;
/

-------------------------------------------------
-- MEDICO
-------------------------------------------------

-- 9. Insertar medico.
CREATE OR REPLACE PROCEDURE SP_INSERTAR_MEDICO (
    P_NOMBRE            IN VARCHAR2,
    P_APELLIDO1         IN VARCHAR2,
    P_APELLIDO2         IN VARCHAR2,
    P_NUMERO_COLEGIADO  IN VARCHAR2,
    P_ESPECIALIDAD      IN VARCHAR2,
    P_TELEFONO          IN VARCHAR2,
    P_CORREO            IN VARCHAR2,
    P_ESTADO            IN VARCHAR2
)
AS
BEGIN
    INSERT INTO MEDICO (
        NOMBRE, APELLIDO1, APELLIDO2, NUMERO_COLEGIADO, ESPECIALIDAD, TELEFONO, CORREO, ESTADO
    ) VALUES (
        P_NOMBRE, P_APELLIDO1, P_APELLIDO2, P_NUMERO_COLEGIADO, P_ESPECIALIDAD, P_TELEFONO, P_CORREO, P_ESTADO
    );
END;
/

-- 10. Consultar medico por ID.
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_MEDICO (
    P_ID_MEDICO IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM MEDICO
        WHERE ID_MEDICO = P_ID_MEDICO;
END;
/

-- 11. Actualizar medico.
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_MEDICO (
    P_ID_MEDICO         IN NUMBER,
    P_NOMBRE            IN VARCHAR2,
    P_APELLIDO1         IN VARCHAR2,
    P_APELLIDO2         IN VARCHAR2,
    P_NUMERO_COLEGIADO  IN VARCHAR2,
    P_ESPECIALIDAD      IN VARCHAR2,
    P_TELEFONO          IN VARCHAR2,
    P_CORREO            IN VARCHAR2,
    P_ESTADO            IN VARCHAR2
)
AS
BEGIN
    UPDATE MEDICO
    SET NOMBRE = P_NOMBRE,
        APELLIDO1 = P_APELLIDO1,
        APELLIDO2 = P_APELLIDO2,
        NUMERO_COLEGIADO = P_NUMERO_COLEGIADO,
        ESPECIALIDAD = P_ESPECIALIDAD,
        TELEFONO = P_TELEFONO,
        CORREO = P_CORREO,
        ESTADO = P_ESTADO
    WHERE ID_MEDICO = P_ID_MEDICO;
END;
/

-- 12. Desactivar medico.
CREATE OR REPLACE PROCEDURE SP_DESACTIVAR_MEDICO (
    P_ID_MEDICO IN NUMBER
)
AS
BEGIN
    UPDATE MEDICO
    SET ESTADO = 'INACTIVO'
    WHERE ID_MEDICO = P_ID_MEDICO;
END;
/

-------------------------------------------------
-- MEDICAMENTO
-------------------------------------------------

-- 13. Insertar medicamento.
CREATE OR REPLACE PROCEDURE SP_INSERTAR_MEDICAMENTO (
    P_CODIGO           IN VARCHAR2,
    P_NOMBRE           IN VARCHAR2,
    P_PRESENTACION     IN VARCHAR2,
    P_REQUIERE_RECETA  IN VARCHAR2,
    P_STOCK_ACTUAL     IN NUMBER,
    P_STOCK_MINIMO     IN NUMBER,
    P_ESTADO           IN VARCHAR2
)
AS
BEGIN
    INSERT INTO MEDICAMENTO (
        CODIGO, NOMBRE, PRESENTACION, REQUIERE_RECETA, STOCK_ACTUAL, STOCK_MINIMO, ESTADO
    ) VALUES (
        P_CODIGO, P_NOMBRE, P_PRESENTACION, P_REQUIERE_RECETA, P_STOCK_ACTUAL, P_STOCK_MINIMO, P_ESTADO
    );
END;
/

-- 14. Consultar medicamento por ID.
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_MEDICAMENTO (
    P_ID_MEDICAMENTO IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM MEDICAMENTO
        WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;
END;
/

-- 15. Actualizar medicamento.
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_MEDICAMENTO (
    P_ID_MEDICAMENTO   IN NUMBER,
    P_CODIGO           IN VARCHAR2,
    P_NOMBRE           IN VARCHAR2,
    P_PRESENTACION     IN VARCHAR2,
    P_REQUIERE_RECETA  IN VARCHAR2,
    P_STOCK_ACTUAL     IN NUMBER,
    P_STOCK_MINIMO     IN NUMBER,
    P_ESTADO           IN VARCHAR2
)
AS
BEGIN
    UPDATE MEDICAMENTO
    SET CODIGO = P_CODIGO,
        NOMBRE = P_NOMBRE,
        PRESENTACION = P_PRESENTACION,
        REQUIERE_RECETA = P_REQUIERE_RECETA,
        STOCK_ACTUAL = P_STOCK_ACTUAL,
        STOCK_MINIMO = P_STOCK_MINIMO,
        ESTADO = P_ESTADO
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;
END;
/

-- 16. Desactivar medicamento.
CREATE OR REPLACE PROCEDURE SP_DESACTIVAR_MEDICAMENTO (
    P_ID_MEDICAMENTO IN NUMBER
)
AS
BEGIN
    UPDATE MEDICAMENTO
    SET ESTADO = 'INACTIVO'
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;
END;
/