-- ============================================
-- CONSTRAINTS Y RELACIONES DEL PROYECTO FARMA
-- ============================================

-- Restricciones de ROL.
ALTER TABLE ROL
ADD CONSTRAINT CK_ROL_ESTADO
CHECK (ESTADO IN ('ACTIVO','INACTIVO'));

-- Restricciones de USUARIO.
ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_ROL
FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL);

ALTER TABLE USUARIO
ADD CONSTRAINT CK_USUARIO_ESTADO
CHECK (ESTADO IN ('ACTIVO','INACTIVO'));

-- Restricciones de PACIENTE.
ALTER TABLE PACIENTE
ADD CONSTRAINT CK_PACIENTE_ESTADO
CHECK (ESTADO IN ('ACTIVO','INACTIVO'));

-- Restricciones de MEDICO.
ALTER TABLE MEDICO
ADD CONSTRAINT CK_MEDICO_ESTADO
CHECK (ESTADO IN ('ACTIVO','INACTIVO'));

-- Restricciones de MEDICAMENTO.
ALTER TABLE MEDICAMENTO
ADD CONSTRAINT CK_MEDICAMENTO_RECETA
CHECK (REQUIERE_RECETA IN ('SI','NO'));

ALTER TABLE MEDICAMENTO
ADD CONSTRAINT CK_MEDICAMENTO_STOCK
CHECK (STOCK_ACTUAL >= 0 AND STOCK_MINIMO >= 0);

ALTER TABLE MEDICAMENTO
ADD CONSTRAINT CK_MEDICAMENTO_ESTADO
CHECK (ESTADO IN ('ACTIVO','INACTIVO'));

-- Restricciones de RECETA.
ALTER TABLE RECETA
ADD CONSTRAINT FK_RECETA_PACIENTE
FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);

ALTER TABLE RECETA
ADD CONSTRAINT FK_RECETA_MEDICO
FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO);

ALTER TABLE RECETA
ADD CONSTRAINT CK_RECETA_ESTADO
CHECK (ESTADO IN ('ACTIVA','COMPLETADA','ANULADA'));

-- Restricciones de RECETA_DETALLE.
ALTER TABLE RECETA_DETALLE
ADD CONSTRAINT FK_RECETA_DETALLE_RECETA
FOREIGN KEY (ID_RECETA) REFERENCES RECETA(ID_RECETA);

ALTER TABLE RECETA_DETALLE
ADD CONSTRAINT FK_RECETA_DETALLE_MEDICAMENTO
FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO);

ALTER TABLE RECETA_DETALLE
ADD CONSTRAINT CK_RECETA_DETALLE_CANTIDADES
CHECK (CANTIDAD_AUTORIZADA > 0 AND CANTIDAD_DISPENSADA >= 0);

ALTER TABLE RECETA_DETALLE
ADD CONSTRAINT UQ_RECETA_DETALLE_UNICO
UNIQUE (ID_RECETA, ID_MEDICAMENTO);

-- Restricciones de DISPENSACION.
ALTER TABLE DISPENSACION
ADD CONSTRAINT FK_DISPENSACION_RECETA
FOREIGN KEY (ID_RECETA) REFERENCES RECETA(ID_RECETA);

ALTER TABLE DISPENSACION
ADD CONSTRAINT FK_DISPENSACION_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE DISPENSACION
ADD CONSTRAINT CK_DISPENSACION_ESTADO
CHECK (ESTADO IN ('ACTIVA','ANULADA'));

-- Restricciones de DISPENSACION_DETALLE.
ALTER TABLE DISPENSACION_DETALLE
ADD CONSTRAINT FK_DISPENSACION_DETALLE_DISP
FOREIGN KEY (ID_DISPENSACION) REFERENCES DISPENSACION(ID_DISPENSACION);

ALTER TABLE DISPENSACION_DETALLE
ADD CONSTRAINT FK_DISPENSACION_DETALLE_RECETA_DET
FOREIGN KEY (ID_RECETA_DETALLE) REFERENCES RECETA_DETALLE(ID_RECETA_DETALLE);

ALTER TABLE DISPENSACION_DETALLE
ADD CONSTRAINT FK_DISPENSACION_DETALLE_MED
FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO);

ALTER TABLE DISPENSACION_DETALLE
ADD CONSTRAINT CK_DISPENSACION_DETALLE_CANT
CHECK (CANTIDAD_DISPENSADA > 0);

-- Restricciones de BITACORA.
ALTER TABLE BITACORA
ADD CONSTRAINT FK_BITACORA_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

-- Restricciones de MOVIMIENTO_INVENTARIO.
ALTER TABLE MOVIMIENTO_INVENTARIO
ADD CONSTRAINT FK_MOVIMIENTO_MEDICAMENTO
FOREIGN KEY (ID_MEDICAMENTO) REFERENCES MEDICAMENTO(ID_MEDICAMENTO);

ALTER TABLE MOVIMIENTO_INVENTARIO
ADD CONSTRAINT FK_MOVIMIENTO_USUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

ALTER TABLE MOVIMIENTO_INVENTARIO
ADD CONSTRAINT CK_MOVIMIENTO_TIPO
CHECK (TIPO_MOVIMIENTO IN ('ENTRADA','SALIDA','AJUSTE','ANULACION'));

ALTER TABLE MOVIMIENTO_INVENTARIO
ADD CONSTRAINT CK_MOVIMIENTO_CANTIDAD
CHECK (CANTIDAD > 0);