CREATE OR REPLACE PROCEDURE SP_DISPENSAR_MEDICAMENTO (
    P_ID_DISPENSACION        IN NUMBER,
    P_ID_RECETA_DETALLE      IN NUMBER,
    P_ID_MEDICAMENTO         IN NUMBER,
    P_CANTIDAD               IN NUMBER
)
AS
    V_STOCK_ACTUAL      NUMBER;
    V_CANTIDAD_PEND     NUMBER;
    V_ID_RECETA         NUMBER;
BEGIN
    SELECT ID_RECETA
    INTO V_ID_RECETA
    FROM RECETA_DETALLE
    WHERE ID_RECETA_DETALLE = P_ID_RECETA_DETALLE;

    V_STOCK_ACTUAL := FN_STOCK_ACTUAL_MEDICAMENTO(P_ID_MEDICAMENTO);
    V_CANTIDAD_PEND := FN_CANT_PENDIENTE_RECETA(P_ID_RECETA_DETALLE);

    IF P_CANTIDAD > V_CANTIDAD_PEND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Cantidad excede lo autorizado');
    END IF;

    IF P_CANTIDAD > V_STOCK_ACTUAL THEN
        RAISE_APPLICATION_ERROR(-20002, 'Stock insuficiente');
    END IF;

    INSERT INTO DISPENSACION_DETALLE (
        ID_DISPENSACION,
        ID_RECETA_DETALLE,
        ID_MEDICAMENTO,
        CANTIDAD_DISPENSADA
    ) VALUES (
        P_ID_DISPENSACION,
        P_ID_RECETA_DETALLE,
        P_ID_MEDICAMENTO,
        P_CANTIDAD
    );

    UPDATE RECETA_DETALLE
    SET CANTIDAD_DISPENSADA = CANTIDAD_DISPENSADA + P_CANTIDAD
    WHERE ID_RECETA_DETALLE = P_ID_RECETA_DETALLE;

    UPDATE MEDICAMENTO
    SET STOCK_ACTUAL = STOCK_ACTUAL - P_CANTIDAD
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

    IF FN_RECETA_COMPLETA(V_ID_RECETA) = 'SI' THEN
        UPDATE RECETA
        SET ESTADO = 'COMPLETADA'
        WHERE ID_RECETA = V_ID_RECETA;
    ELSE
        UPDATE RECETA
        SET ESTADO = 'ACTIVA'
        WHERE ID_RECETA = V_ID_RECETA;
    END IF;
END;
/