CREATE OR REPLACE PROCEDURE SP_ANULAR_DISPENSACION (
    P_ID_DISPENSACION IN NUMBER
)
AS
    CURSOR C_DETALLES IS
        SELECT ID_RECETA_DETALLE, ID_MEDICAMENTO, CANTIDAD_DISPENSADA
        FROM DISPENSACION_DETALLE
        WHERE ID_DISPENSACION = P_ID_DISPENSACION;

    V_ID_RECETA NUMBER;
BEGIN
    SELECT ID_RECETA
    INTO V_ID_RECETA
    FROM DISPENSACION
    WHERE ID_DISPENSACION = P_ID_DISPENSACION;

    FOR R IN C_DETALLES LOOP
        UPDATE RECETA_DETALLE
        SET CANTIDAD_DISPENSADA = CANTIDAD_DISPENSADA - R.CANTIDAD_DISPENSADA
        WHERE ID_RECETA_DETALLE = R.ID_RECETA_DETALLE;

        UPDATE MEDICAMENTO
        SET STOCK_ACTUAL = STOCK_ACTUAL + R.CANTIDAD_DISPENSADA
        WHERE ID_MEDICAMENTO = R.ID_MEDICAMENTO;

        INSERT INTO MOVIMIENTO_INVENTARIO (
            ID_MEDICAMENTO,
            TIPO_MOVIMIENTO,
            CANTIDAD,
            MOTIVO,
            FECHA_MOVIMIENTO,
            ID_USUARIO
        ) VALUES (
            R.ID_MEDICAMENTO,
            'ANULACION',
            R.CANTIDAD_DISPENSADA,
            'Devolucion por anulacion de dispensacion',
            SYSDATE,
            1
        );
    END LOOP;

    UPDATE DISPENSACION
    SET ESTADO = 'ANULADA'
    WHERE ID_DISPENSACION = P_ID_DISPENSACION;

    IF FN_RECETA_COMPLETA(V_ID_RECETA) = 'SI' THEN
        UPDATE RECETA
        SET ESTADO = 'COMPLETADA'
        WHERE ID_RECETA = V_ID_RECETA;
    ELSE
        UPDATE RECETA
        SET ESTADO = 'ACTIVA'
        WHERE ID_RECETA = V_ID_RECETA;
    END IF;

    INSERT INTO BITACORA (
        ID_USUARIO,
        ACCION,
        ENTIDAD_AFECTADA,
        ID_REFERENCIA,
        FECHA_HORA,
        DETALLE
    ) VALUES (
        1,
        'ANULAR',
        'DISPENSACION',
        P_ID_DISPENSACION,
        SYSDATE,
        'Se anulo una dispensacion y se devolvio stock'
    );
END;
/