CREATE OR REPLACE PROCEDURE SP_LISTAR_PACIENTES (
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM PACIENTE
        ORDER BY ID_PACIENTE;
END;
/

CREATE OR REPLACE PROCEDURE SP_LISTAR_MEDICAMENTOS (
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM MEDICAMENTO
        ORDER BY ID_MEDICAMENTO;
END;
/