CREATE OR REPLACE PROCEDURE SP_LOGIN_USUARIO (
    P_USERNAME IN VARCHAR2,
    P_CLAVE    IN VARCHAR2,
    P_CURSOR   OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM USUARIO
        WHERE USERNAME = P_USERNAME
          AND CLAVE = P_CLAVE
          AND ESTADO = 'ACTIVO';
END;
/