-- ============================================
-- PROCEDIMIENTOS PARTE 2 - FARMA
-- LOGICA DE RECETA, DISPENSACION, BITACORA E INVENTARIO
-- ============================================

-------------------------------------------------
-- RECETA
-------------------------------------------------

-- 17. Insertar receta.
CREATE OR REPLACE PROCEDURE SP_INSERTAR_RECETA (
    P_ID_PACIENTE    IN NUMBER,
    P_ID_MEDICO      IN NUMBER,
    P_OBSERVACIONES  IN VARCHAR2
)
AS
BEGIN
    INSERT INTO RECETA (
        ID_PACIENTE, ID_MEDICO, FECHA_EMISION, ESTADO, OBSERVACIONES
    ) VALUES (
        P_ID_PACIENTE, P_ID_MEDICO, SYSDATE, 'ACTIVA', P_OBSERVACIONES
    );
END;
/

-- 18. Consultar receta por ID.
CREATE OR REPLACE PROCEDURE SP_CONSULTAR_RECETA (
    P_ID_RECETA IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT *
        FROM VW_RECETAS_ENCABEZADO
        WHERE ID_RECETA = P_ID_RECETA;
END;
/

-- 19. Insertar detalle de receta.
CREATE OR REPLACE PROCEDURE SP_INSERTAR_RECETA_DETALLE (
    P_ID_RECETA             IN NUMBER,
    P_ID_MEDICAMENTO        IN NUMBER,
    P_DOSIS                 IN VARCHAR2,
    P_CANTIDAD_AUTORIZADA   IN NUMBER,
    P_INDICACIONES          IN VARCHAR2
)
AS
BEGIN
    INSERT INTO RECETA_DETALLE (
        ID_RECETA, ID_MEDICAMENTO, DOSIS, CANTIDAD_AUTORIZADA, CANTIDAD_DISPENSADA, INDICACIONES
    ) VALUES (
        P_ID_RECETA, P_ID_MEDICAMENTO, P_DOSIS, P_CANTIDAD_AUTORIZADA, 0, P_INDICACIONES
    );
END;
/

-- 20. Actualizar estado de receta.
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_ESTADO_RECETA (
    P_ID_RECETA IN NUMBER,
    P_ESTADO    IN VARCHAR2
)
AS
BEGIN
    UPDATE RECETA
    SET ESTADO = P_ESTADO
    WHERE ID_RECETA = P_ID_RECETA;
END;
/

-------------------------------------------------
-- DISPENSACION
-------------------------------------------------

-- 21. Insertar encabezado de dispensacion.
CREATE OR REPLACE PROCEDURE SP_INSERTAR_DISPENSACION (
    P_ID_RECETA        IN NUMBER,
    P_ID_USUARIO       IN NUMBER,
    P_OBSERVACIONES    IN VARCHAR2
)
AS
BEGIN
    INSERT INTO DISPENSACION (
        ID_RECETA, ID_USUARIO, FECHA_DISPENSACION, ESTADO, OBSERVACIONES
    ) VALUES (
        P_ID_RECETA, P_ID_USUARIO, SYSDATE, 'ACTIVA', P_OBSERVACIONES
    );
END;
/

-- 22. Insertar detalle de dispensacion.
CREATE OR REPLACE PROCEDURE SP_INSERTAR_DISPENSACION_DETALLE (
    P_ID_DISPENSACION        IN NUMBER,
    P_ID_RECETA_DETALLE      IN NUMBER,
    P_ID_MEDICAMENTO         IN NUMBER,
    P_CANTIDAD_DISPENSADA    IN NUMBER
)
AS
BEGIN
    INSERT INTO DISPENSACION_DETALLE (
        ID_DISPENSACION, ID_RECETA_DETALLE, ID_MEDICAMENTO, CANTIDAD_DISPENSADA
    ) VALUES (
        P_ID_DISPENSACION, P_ID_RECETA_DETALLE, P_ID_MEDICAMENTO, P_CANTIDAD_DISPENSADA
    );
END;
/

-- 23. Dispensar medicamento con actualizacion de receta e inventario.
CREATE OR REPLACE PROCEDURE SP_DISPENSAR_MEDICAMENTO (
    P_ID_DISPENSACION        IN NUMBER,
    P_ID_RECETA_DETALLE      IN NUMBER,
    P_ID_MEDICAMENTO         IN NUMBER,
    P_CANTIDAD               IN NUMBER
)
AS
    V_STOCK_ACTUAL      NUMBER;
    V_CANTIDAD_PEND     NUMBER;
BEGIN
    V_STOCK_ACTUAL := FN_STOCK_ACTUAL_MEDICAMENTO(P_ID_MEDICAMENTO);
    V_CANTIDAD_PEND := FN_CANT_PENDIENTE_RECETA(P_ID_RECETA_DETALLE);

    IF P_CANTIDAD > V_CANTIDAD_PEND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Cantidad excede lo autorizado');
    END IF;

    IF P_CANTIDAD > V_STOCK_ACTUAL THEN
        RAISE_APPLICATION_ERROR(-20002, 'Stock insuficiente');
    END IF;

    INSERT INTO DISPENSACION_DETALLE (
        ID_DISPENSACION, ID_RECETA_DETALLE, ID_MEDICAMENTO, CANTIDAD_DISPENSADA
    ) VALUES (
        P_ID_DISPENSACION, P_ID_RECETA_DETALLE, P_ID_MEDICAMENTO, P_CANTIDAD
    );

    UPDATE RECETA_DETALLE
    SET CANTIDAD_DISPENSADA = CANTIDAD_DISPENSADA + P_CANTIDAD
    WHERE ID_RECETA_DETALLE = P_ID_RECETA_DETALLE;

    UPDATE MEDICAMENTO
    SET STOCK_ACTUAL = STOCK_ACTUAL - P_CANTIDAD
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;
END;
/

-- 24. Anular dispensacion.
CREATE OR REPLACE PROCEDURE SP_ANULAR_DISPENSACION (
    P_ID_DISPENSACION IN NUMBER
)
AS
BEGIN
    UPDATE DISPENSACION
    SET ESTADO = 'ANULADA'
    WHERE ID_DISPENSACION = P_ID_DISPENSACION;
END;
/

-------------------------------------------------
-- BITACORA / INVENTARIO
-------------------------------------------------

-- 25. Registrar bitacora.
CREATE OR REPLACE PROCEDURE SP_REGISTRAR_BITACORA (
    P_ID_USUARIO        IN NUMBER,
    P_ACCION            IN VARCHAR2,
    P_ENTIDAD_AFECTADA  IN VARCHAR2,
    P_ID_REFERENCIA     IN NUMBER,
    P_DETALLE           IN VARCHAR2
)
AS
BEGIN
    INSERT INTO BITACORA (
        ID_USUARIO, ACCION, ENTIDAD_AFECTADA, ID_REFERENCIA, FECHA_HORA, DETALLE
    ) VALUES (
        P_ID_USUARIO, P_ACCION, P_ENTIDAD_AFECTADA, P_ID_REFERENCIA, SYSDATE, P_DETALLE
    );
END;
/