-- ============================================
-- VISTAS DEL PROYECTO FARMA
-- ============================================

-- 1. Vista de usuarios con su rol.
CREATE OR REPLACE VIEW VW_USUARIOS_ROL AS
SELECT
    U.ID_USUARIO,
    U.CEDULA,
    U.NOMBRE,
    U.APELLIDO1,
    U.APELLIDO2,
    U.CORREO,
    U.USERNAME,
    U.ESTADO,
    R.ID_ROL,
    R.NOMBRE AS NOMBRE_ROL
FROM USUARIO U
INNER JOIN ROL R
    ON U.ID_ROL = R.ID_ROL;

-- 2. Vista de pacientes activos.
CREATE OR REPLACE VIEW VW_PACIENTES_ACTIVOS AS
SELECT
    ID_PACIENTE,
    CEDULA,
    NOMBRE,
    APELLIDO1,
    APELLIDO2,
    TELEFONO,
    CORREO,
    ESTADO
FROM PACIENTE
WHERE ESTADO = 'ACTIVO';

-- 3. Vista de medicos activos.
CREATE OR REPLACE VIEW VW_MEDICOS_ACTIVOS AS
SELECT
    ID_MEDICO,
    NOMBRE,
    APELLIDO1,
    APELLIDO2,
    NUMERO_COLEGIADO,
    ESPECIALIDAD,
    TELEFONO,
    CORREO,
    ESTADO
FROM MEDICO
WHERE ESTADO = 'ACTIVO';

-- 4. Vista de medicamentos activos.
CREATE OR REPLACE VIEW VW_MEDICAMENTOS_ACTIVOS AS
SELECT
    ID_MEDICAMENTO,
    CODIGO,
    NOMBRE,
    PRESENTACION,
    REQUIERE_RECETA,
    STOCK_ACTUAL,
    STOCK_MINIMO,
    ESTADO
FROM MEDICAMENTO
WHERE ESTADO = 'ACTIVO';

-- 5. Vista de encabezado de recetas.
CREATE OR REPLACE VIEW VW_RECETAS_ENCABEZADO AS
SELECT
    R.ID_RECETA,
    R.FECHA_EMISION,
    R.ESTADO,
    R.OBSERVACIONES,
    P.ID_PACIENTE,
    P.CEDULA AS CEDULA_PACIENTE,
    P.NOMBRE AS NOMBRE_PACIENTE,
    P.APELLIDO1 AS APELLIDO1_PACIENTE,
    P.APELLIDO2 AS APELLIDO2_PACIENTE,
    M.ID_MEDICO,
    M.NOMBRE AS NOMBRE_MEDICO,
    M.APELLIDO1 AS APELLIDO1_MEDICO,
    M.APELLIDO2 AS APELLIDO2_MEDICO,
    M.NUMERO_COLEGIADO
FROM RECETA R
INNER JOIN PACIENTE P
    ON R.ID_PACIENTE = P.ID_PACIENTE
INNER JOIN MEDICO M
    ON R.ID_MEDICO = M.ID_MEDICO;

-- 6. Vista de detalle completo de receta.
CREATE OR REPLACE VIEW VW_RECETA_DETALLE_COMPLETO AS
SELECT
    RD.ID_RECETA_DETALLE,
    RD.ID_RECETA,
    RD.ID_MEDICAMENTO,
    MED.CODIGO,
    MED.NOMBRE AS NOMBRE_MEDICAMENTO,
    MED.PRESENTACION,
    RD.DOSIS,
    RD.CANTIDAD_AUTORIZADA,
    RD.CANTIDAD_DISPENSADA,
    (RD.CANTIDAD_AUTORIZADA - RD.CANTIDAD_DISPENSADA) AS CANTIDAD_PENDIENTE,
    RD.INDICACIONES
FROM RECETA_DETALLE RD
INNER JOIN MEDICAMENTO MED
    ON RD.ID_MEDICAMENTO = MED.ID_MEDICAMENTO;

-- 7. Vista de recetas pendientes.
CREATE OR REPLACE VIEW VW_RECETAS_PENDIENTES AS
SELECT
    R.ID_RECETA,
    P.NOMBRE || ' ' || P.APELLIDO1 || ' ' || NVL(P.APELLIDO2, '') AS PACIENTE,
    M.NOMBRE || ' ' || M.APELLIDO1 || ' ' || NVL(M.APELLIDO2, '') AS MEDICO,
    R.FECHA_EMISION,
    R.ESTADO
FROM RECETA R
INNER JOIN PACIENTE P
    ON R.ID_PACIENTE = P.ID_PACIENTE
INNER JOIN MEDICO M
    ON R.ID_MEDICO = M.ID_MEDICO
WHERE R.ESTADO = 'ACTIVA';

-- 8. Vista de encabezado de dispensaciones.
CREATE OR REPLACE VIEW VW_DISPENSACIONES_ENCABEZADO AS
SELECT
    D.ID_DISPENSACION,
    D.ID_RECETA,
    D.FECHA_DISPENSACION,
    D.ESTADO,
    U.ID_USUARIO,
    U.NOMBRE || ' ' || U.APELLIDO1 || ' ' || NVL(U.APELLIDO2, '') AS USUARIO_RESPONSABLE
FROM DISPENSACION D
INNER JOIN USUARIO U
    ON D.ID_USUARIO = U.ID_USUARIO;

-- 9. Vista de medicamentos con stock bajo.
CREATE OR REPLACE VIEW VW_STOCK_BAJO AS
SELECT
    ID_MEDICAMENTO,
    CODIGO,
    NOMBRE,
    PRESENTACION,
    STOCK_ACTUAL,
    STOCK_MINIMO,
    ESTADO
FROM MEDICAMENTO
WHERE STOCK_ACTUAL <= STOCK_MINIMO;

-- 10. Vista de bitacora resumen.
CREATE OR REPLACE VIEW VW_BITACORA_RESUMEN AS
SELECT
    B.ID_BITACORA,
    B.ACCION,
    B.ENTIDAD_AFECTADA,
    B.ID_REFERENCIA,
    B.FECHA_HORA,
    B.DETALLE,
    U.USERNAME,
    U.NOMBRE,
    U.APELLIDO1
FROM BITACORA B
INNER JOIN USUARIO U
    ON B.ID_USUARIO = U.ID_USUARIO;