-- ============================================
-- PAQUETES PARTE 1 - FARMA
-- ============================================

-------------------------------------------------
-- 1. PKG_USUARIO
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_USUARIO AS
    PROCEDURE PR_INSERTAR_USUARIO (
        P_ID_ROL         IN NUMBER,
        P_CEDULA         IN VARCHAR2,
        P_NOMBRE         IN VARCHAR2,
        P_APELLIDO1      IN VARCHAR2,
        P_APELLIDO2      IN VARCHAR2,
        P_CORREO         IN VARCHAR2,
        P_USERNAME       IN VARCHAR2,
        P_CLAVE          IN VARCHAR2,
        P_ESTADO         IN VARCHAR2
    );

    PROCEDURE PR_CONSULTAR_USUARIO (
        P_ID_USUARIO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );

    FUNCTION FN_OBTENER_NOMBRE_USUARIO (
        P_ID_USUARIO IN NUMBER
    ) RETURN VARCHAR2;
END PKG_USUARIO;
/
CREATE OR REPLACE PACKAGE BODY PKG_USUARIO AS
    PROCEDURE PR_INSERTAR_USUARIO (
        P_ID_ROL         IN NUMBER,
        P_CEDULA         IN VARCHAR2,
        P_NOMBRE         IN VARCHAR2,
        P_APELLIDO1      IN VARCHAR2,
        P_APELLIDO2      IN VARCHAR2,
        P_CORREO         IN VARCHAR2,
        P_USERNAME       IN VARCHAR2,
        P_CLAVE          IN VARCHAR2,
        P_ESTADO         IN VARCHAR2
    )
    AS
    BEGIN
        SP_INSERTAR_USUARIO(
            P_ID_ROL, P_CEDULA, P_NOMBRE, P_APELLIDO1, P_APELLIDO2,
            P_CORREO, P_USERNAME, P_CLAVE, P_ESTADO
        );
    END;

    PROCEDURE PR_CONSULTAR_USUARIO (
        P_ID_USUARIO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        SP_CONSULTAR_USUARIO(P_ID_USUARIO, P_CURSOR);
    END;

    FUNCTION FN_OBTENER_NOMBRE_USUARIO (
        P_ID_USUARIO IN NUMBER
    ) RETURN VARCHAR2
    AS
    BEGIN
        RETURN FN_NOMBRE_COMPLETO_USUARIO(P_ID_USUARIO);
    END;
END PKG_USUARIO;
/

-------------------------------------------------
-- 2. PKG_PACIENTE
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_PACIENTE AS
    PROCEDURE PR_INSERTAR_PACIENTE (
        P_CEDULA     IN VARCHAR2,
        P_NOMBRE     IN VARCHAR2,
        P_APELLIDO1  IN VARCHAR2,
        P_APELLIDO2  IN VARCHAR2,
        P_TELEFONO   IN VARCHAR2,
        P_CORREO     IN VARCHAR2,
        P_ESTADO     IN VARCHAR2
    );

    PROCEDURE PR_CONSULTAR_PACIENTE (
        P_ID_PACIENTE IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );

    FUNCTION FN_OBTENER_NOMBRE_PACIENTE (
        P_ID_PACIENTE IN NUMBER
    ) RETURN VARCHAR2;
END PKG_PACIENTE;
/
CREATE OR REPLACE PACKAGE BODY PKG_PACIENTE AS
    PROCEDURE PR_INSERTAR_PACIENTE (
        P_CEDULA     IN VARCHAR2,
        P_NOMBRE     IN VARCHAR2,
        P_APELLIDO1  IN VARCHAR2,
        P_APELLIDO2  IN VARCHAR2,
        P_TELEFONO   IN VARCHAR2,
        P_CORREO     IN VARCHAR2,
        P_ESTADO     IN VARCHAR2
    )
    AS
    BEGIN
        SP_INSERTAR_PACIENTE(
            P_CEDULA, P_NOMBRE, P_APELLIDO1, P_APELLIDO2,
            P_TELEFONO, P_CORREO, P_ESTADO
        );
    END;

    PROCEDURE PR_CONSULTAR_PACIENTE (
        P_ID_PACIENTE IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        SP_CONSULTAR_PACIENTE(P_ID_PACIENTE, P_CURSOR);
    END;

    FUNCTION FN_OBTENER_NOMBRE_PACIENTE (
        P_ID_PACIENTE IN NUMBER
    ) RETURN VARCHAR2
    AS
    BEGIN
        RETURN FN_NOMBRE_COMPLETO_PACIENTE(P_ID_PACIENTE);
    END;
END PKG_PACIENTE;
/

-------------------------------------------------
-- 3. PKG_MEDICO
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_MEDICO AS
    PROCEDURE PR_INSERTAR_MEDICO (
        P_NOMBRE            IN VARCHAR2,
        P_APELLIDO1         IN VARCHAR2,
        P_APELLIDO2         IN VARCHAR2,
        P_NUMERO_COLEGIADO  IN VARCHAR2,
        P_ESPECIALIDAD      IN VARCHAR2,
        P_TELEFONO          IN VARCHAR2,
        P_CORREO            IN VARCHAR2,
        P_ESTADO            IN VARCHAR2
    );

    PROCEDURE PR_CONSULTAR_MEDICO (
        P_ID_MEDICO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );

    FUNCTION FN_OBTENER_NOMBRE_MEDICO (
        P_ID_MEDICO IN NUMBER
    ) RETURN VARCHAR2;
END PKG_MEDICO;
/
CREATE OR REPLACE PACKAGE BODY PKG_MEDICO AS
    PROCEDURE PR_INSERTAR_MEDICO (
        P_NOMBRE            IN VARCHAR2,
        P_APELLIDO1         IN VARCHAR2,
        P_APELLIDO2         IN VARCHAR2,
        P_NUMERO_COLEGIADO  IN VARCHAR2,
        P_ESPECIALIDAD      IN VARCHAR2,
        P_TELEFONO          IN VARCHAR2,
        P_CORREO            IN VARCHAR2,
        P_ESTADO            IN VARCHAR2
    )
    AS
    BEGIN
        SP_INSERTAR_MEDICO(
            P_NOMBRE, P_APELLIDO1, P_APELLIDO2, P_NUMERO_COLEGIADO,
            P_ESPECIALIDAD, P_TELEFONO, P_CORREO, P_ESTADO
        );
    END;

    PROCEDURE PR_CONSULTAR_MEDICO (
        P_ID_MEDICO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        SP_CONSULTAR_MEDICO(P_ID_MEDICO, P_CURSOR);
    END;

    FUNCTION FN_OBTENER_NOMBRE_MEDICO (
        P_ID_MEDICO IN NUMBER
    ) RETURN VARCHAR2
    AS
    BEGIN
        RETURN FN_NOMBRE_COMPLETO_MEDICO(P_ID_MEDICO);
    END;
END PKG_MEDICO;
/

-------------------------------------------------
-- 4. PKG_MEDICAMENTO
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_MEDICAMENTO AS
    PROCEDURE PR_INSERTAR_MEDICAMENTO (
        P_CODIGO           IN VARCHAR2,
        P_NOMBRE           IN VARCHAR2,
        P_PRESENTACION     IN VARCHAR2,
        P_REQUIERE_RECETA  IN VARCHAR2,
        P_STOCK_ACTUAL     IN NUMBER,
        P_STOCK_MINIMO     IN NUMBER,
        P_ESTADO           IN VARCHAR2
    );

    PROCEDURE PR_CONSULTAR_MEDICAMENTO (
        P_ID_MEDICAMENTO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );

    FUNCTION FN_OBTENER_STOCK (
        P_ID_MEDICAMENTO IN NUMBER
    ) RETURN NUMBER;
END PKG_MEDICAMENTO;
/
CREATE OR REPLACE PACKAGE BODY PKG_MEDICAMENTO AS
    PROCEDURE PR_INSERTAR_MEDICAMENTO (
        P_CODIGO           IN VARCHAR2,
        P_NOMBRE           IN VARCHAR2,
        P_PRESENTACION     IN VARCHAR2,
        P_REQUIERE_RECETA  IN VARCHAR2,
        P_STOCK_ACTUAL     IN NUMBER,
        P_STOCK_MINIMO     IN NUMBER,
        P_ESTADO           IN VARCHAR2
    )
    AS
    BEGIN
        SP_INSERTAR_MEDICAMENTO(
            P_CODIGO, P_NOMBRE, P_PRESENTACION,
            P_REQUIERE_RECETA, P_STOCK_ACTUAL, P_STOCK_MINIMO, P_ESTADO
        );
    END;

    PROCEDURE PR_CONSULTAR_MEDICAMENTO (
        P_ID_MEDICAMENTO IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        SP_CONSULTAR_MEDICAMENTO(P_ID_MEDICAMENTO, P_CURSOR);
    END;

    FUNCTION FN_OBTENER_STOCK (
        P_ID_MEDICAMENTO IN NUMBER
    ) RETURN NUMBER
    AS
    BEGIN
        RETURN FN_STOCK_ACTUAL_MEDICAMENTO(P_ID_MEDICAMENTO);
    END;
END PKG_MEDICAMENTO;
/

-------------------------------------------------
-- 5. PKG_RECETA
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_RECETA AS
    PROCEDURE PR_INSERTAR_RECETA (
        P_ID_PACIENTE    IN NUMBER,
        P_ID_MEDICO      IN NUMBER,
        P_OBSERVACIONES  IN VARCHAR2
    );

    PROCEDURE PR_CONSULTAR_RECETA (
        P_ID_RECETA IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );

    FUNCTION FN_RECETA_ESTA_COMPLETA (
        P_ID_RECETA IN NUMBER
    ) RETURN VARCHAR2;
END PKG_RECETA;
/
CREATE OR REPLACE PACKAGE BODY PKG_RECETA AS
    PROCEDURE PR_INSERTAR_RECETA (
        P_ID_PACIENTE    IN NUMBER,
        P_ID_MEDICO      IN NUMBER,
        P_OBSERVACIONES  IN VARCHAR2
    )
    AS
    BEGIN
        SP_INSERTAR_RECETA(P_ID_PACIENTE, P_ID_MEDICO, P_OBSERVACIONES);
    END;

    PROCEDURE PR_CONSULTAR_RECETA (
        P_ID_RECETA IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        SP_CONSULTAR_RECETA(P_ID_RECETA, P_CURSOR);
    END;

    FUNCTION FN_RECETA_ESTA_COMPLETA (
        P_ID_RECETA IN NUMBER
    ) RETURN VARCHAR2
    AS
    BEGIN
        RETURN FN_RECETA_COMPLETA(P_ID_RECETA);
    END;
END PKG_RECETA;
/