-- ============================================
-- PAQUETES PARTE 2 - FARMA
-- ============================================

-------------------------------------------------
-- 6. PKG_DISPENSACION
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_DISPENSACION AS
    PROCEDURE PR_INSERTAR_DISPENSACION (
        P_ID_RECETA        IN NUMBER,
        P_ID_USUARIO       IN NUMBER,
        P_OBSERVACIONES    IN VARCHAR2
    );

    PROCEDURE PR_DISPENSAR_MEDICAMENTO (
        P_ID_DISPENSACION        IN NUMBER,
        P_ID_RECETA_DETALLE      IN NUMBER,
        P_ID_MEDICAMENTO         IN NUMBER,
        P_CANTIDAD               IN NUMBER
    );

    PROCEDURE PR_ANULAR_DISPENSACION (
        P_ID_DISPENSACION IN NUMBER
    );
END PKG_DISPENSACION;
/
CREATE OR REPLACE PACKAGE BODY PKG_DISPENSACION AS
    PROCEDURE PR_INSERTAR_DISPENSACION (
        P_ID_RECETA        IN NUMBER,
        P_ID_USUARIO       IN NUMBER,
        P_OBSERVACIONES    IN VARCHAR2
    )
    AS
    BEGIN
        SP_INSERTAR_DISPENSACION(P_ID_RECETA, P_ID_USUARIO, P_OBSERVACIONES);
    END;

    PROCEDURE PR_DISPENSAR_MEDICAMENTO (
        P_ID_DISPENSACION        IN NUMBER,
        P_ID_RECETA_DETALLE      IN NUMBER,
        P_ID_MEDICAMENTO         IN NUMBER,
        P_CANTIDAD               IN NUMBER
    )
    AS
    BEGIN
        SP_DISPENSAR_MEDICAMENTO(
            P_ID_DISPENSACION, P_ID_RECETA_DETALLE, P_ID_MEDICAMENTO, P_CANTIDAD
        );
    END;

    PROCEDURE PR_ANULAR_DISPENSACION (
        P_ID_DISPENSACION IN NUMBER
    )
    AS
    BEGIN
        SP_ANULAR_DISPENSACION(P_ID_DISPENSACION);
    END;
END PKG_DISPENSACION;
/

-------------------------------------------------
-- 7. PKG_BITACORA
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_BITACORA AS
    PROCEDURE PR_REGISTRAR_BITACORA (
        P_ID_USUARIO        IN NUMBER,
        P_ACCION            IN VARCHAR2,
        P_ENTIDAD_AFECTADA  IN VARCHAR2,
        P_ID_REFERENCIA     IN NUMBER,
        P_DETALLE           IN VARCHAR2
    );

    PROCEDURE PR_CONSULTAR_BITACORA (
        P_CURSOR OUT SYS_REFCURSOR
    );
END PKG_BITACORA;
/
CREATE OR REPLACE PACKAGE BODY PKG_BITACORA AS
    PROCEDURE PR_REGISTRAR_BITACORA (
        P_ID_USUARIO        IN NUMBER,
        P_ACCION            IN VARCHAR2,
        P_ENTIDAD_AFECTADA  IN VARCHAR2,
        P_ID_REFERENCIA     IN NUMBER,
        P_DETALLE           IN VARCHAR2
    )
    AS
    BEGIN
        SP_REGISTRAR_BITACORA(
            P_ID_USUARIO, P_ACCION, P_ENTIDAD_AFECTADA, P_ID_REFERENCIA, P_DETALLE
        );
    END;

    PROCEDURE PR_CONSULTAR_BITACORA (
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
            FROM VW_BITACORA_RESUMEN
            ORDER BY FECHA_HORA DESC;
    END;
END PKG_BITACORA;
/

-------------------------------------------------
-- 8. PKG_INVENTARIO
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_INVENTARIO AS
    FUNCTION FN_STOCK_ACTUAL (
        P_ID_MEDICAMENTO IN NUMBER
    ) RETURN NUMBER;

    FUNCTION FN_STOCK_MINIMO (
        P_ID_MEDICAMENTO IN NUMBER
    ) RETURN NUMBER;

    PROCEDURE PR_AJUSTAR_STOCK (
        P_ID_MEDICAMENTO IN NUMBER,
        P_CANTIDAD       IN NUMBER
    );
END PKG_INVENTARIO;
/
CREATE OR REPLACE PACKAGE BODY PKG_INVENTARIO AS
    FUNCTION FN_STOCK_ACTUAL (
        P_ID_MEDICAMENTO IN NUMBER
    ) RETURN NUMBER
    AS
    BEGIN
        RETURN FN_STOCK_ACTUAL_MEDICAMENTO(P_ID_MEDICAMENTO);
    END;

    FUNCTION FN_STOCK_MINIMO (
        P_ID_MEDICAMENTO IN NUMBER
    ) RETURN NUMBER
    AS
    BEGIN
        RETURN FN_STOCK_MINIMO_MEDICAMENTO(P_ID_MEDICAMENTO);
    END;

    PROCEDURE PR_AJUSTAR_STOCK (
        P_ID_MEDICAMENTO IN NUMBER,
        P_CANTIDAD       IN NUMBER
    )
    AS
    BEGIN
        UPDATE MEDICAMENTO
        SET STOCK_ACTUAL = STOCK_ACTUAL + P_CANTIDAD
        WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;
    END;
END PKG_INVENTARIO;
/

-------------------------------------------------
-- 9. PKG_REPORTES
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_REPORTES AS
    PROCEDURE PR_REPORTE_RECETAS_ACTIVAS (
        P_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PR_REPORTE_STOCK_BAJO (
        P_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE PR_REPORTE_DISPENSACIONES (
        P_CURSOR OUT SYS_REFCURSOR
    );
END PKG_REPORTES;
/
CREATE OR REPLACE PACKAGE BODY PKG_REPORTES AS
    PROCEDURE PR_REPORTE_RECETAS_ACTIVAS (
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
            FROM VW_RECETAS_PENDIENTES;
    END;

    PROCEDURE PR_REPORTE_STOCK_BAJO (
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
            FROM VW_STOCK_BAJO;
    END;

    PROCEDURE PR_REPORTE_DISPENSACIONES (
        P_CURSOR OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        OPEN P_CURSOR FOR
            SELECT *
            FROM VW_DISPENSACIONES_ENCABEZADO;
    END;
END PKG_REPORTES;
/

-------------------------------------------------
-- 10. PKG_VALIDACIONES
-------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_VALIDACIONES AS
    FUNCTION FN_PACIENTE_ACTIVO_PKG (
        P_ID_PACIENTE IN NUMBER
    ) RETURN VARCHAR2;

    FUNCTION FN_MEDICO_ACTIVO_PKG (
        P_ID_MEDICO IN NUMBER
    ) RETURN VARCHAR2;

    FUNCTION FN_USUARIO_ACTIVO_PKG (
        P_ID_USUARIO IN NUMBER
    ) RETURN VARCHAR2;
END PKG_VALIDACIONES;
/
CREATE OR REPLACE PACKAGE BODY PKG_VALIDACIONES AS
    FUNCTION FN_PACIENTE_ACTIVO_PKG (
        P_ID_PACIENTE IN NUMBER
    ) RETURN VARCHAR2
    AS
    BEGIN
        RETURN FN_PACIENTE_ACTIVO(P_ID_PACIENTE);
    END;

    FUNCTION FN_MEDICO_ACTIVO_PKG (
        P_ID_MEDICO IN NUMBER
    ) RETURN VARCHAR2
    AS
    BEGIN
        RETURN FN_MEDICO_ACTIVO(P_ID_MEDICO);
    END;

    FUNCTION FN_USUARIO_ACTIVO_PKG (
        P_ID_USUARIO IN NUMBER
    ) RETURN VARCHAR2
    AS
    BEGIN
        RETURN FN_USUARIO_ACTIVO(P_ID_USUARIO);
    END;
END PKG_VALIDACIONES;
/