-- ============================================
-- DATOS DE PRUEBA DEL PROYECTO FARMA
-- ============================================

-- ROLES
INSERT INTO ROL (NOMBRE, DESCRIPCION, ESTADO)
VALUES ('ADMINISTRADOR', 'Control total del sistema', 'ACTIVO');

INSERT INTO ROL (NOMBRE, DESCRIPCION, ESTADO)
VALUES ('FARMACEUTICO', 'Dispensacion y consulta de recetas', 'ACTIVO');


-- USUARIOS
INSERT INTO USUARIO (
    ID_ROL, CEDULA, NOMBRE, APELLIDO1, APELLIDO2, CORREO, USERNAME, CLAVE, ESTADO
) VALUES (
    1, '1-1111-1111', 'Adrian', 'Gonzalez', 'Chinchilla', 'admin@farma.com', 'admin', 'admin123', 'ACTIVO'
);

INSERT INTO USUARIO (
    ID_ROL, CEDULA, NOMBRE, APELLIDO1, APELLIDO2, CORREO, USERNAME, CLAVE, ESTADO
) VALUES (
    2, '2-2222-2222', 'Rosa', 'Garro', 'Rojas', 'farmaceutico@farma.com', 'rosa', 'rosa123', 'ACTIVO'
);


-- PACIENTES
INSERT INTO PACIENTE (
    CEDULA, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, CORREO, ESTADO
) VALUES (
    '3-3333-3333', 'Carlos', 'Ramirez', 'Lopez', '88887777', 'carlos@email.com', 'ACTIVO'
);

INSERT INTO PACIENTE (
    CEDULA, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, CORREO, ESTADO
) VALUES (
    '4-4444-4444', 'Maria', 'Fernandez', 'Soto', '87776666', 'maria@email.com', 'ACTIVO'
);

INSERT INTO PACIENTE (
    CEDULA, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, CORREO, ESTADO
) VALUES (
    '5-5555-5555', 'Jose', 'Vargas', 'Mora', '86665555', 'jose@email.com', 'ACTIVO'
);


-- MEDICOS
INSERT INTO MEDICO (
    NOMBRE, APELLIDO1, APELLIDO2, NUMERO_COLEGIADO, ESPECIALIDAD, TELEFONO, CORREO, ESTADO
) VALUES (
    'Ana', 'Rojas', 'Castro', 'COL-1001', 'Medicina General', '88880001', 'ana.rojas@med.com', 'ACTIVO'
);

INSERT INTO MEDICO (
    NOMBRE, APELLIDO1, APELLIDO2, NUMERO_COLEGIADO, ESPECIALIDAD, TELEFONO, CORREO, ESTADO
) VALUES (
    'Luis', 'Mendez', 'Araya', 'COL-1002', 'Pediatria', '88880002', 'luis.mendez@med.com', 'ACTIVO'
);


-- MEDICAMENTOS
INSERT INTO MEDICAMENTO (
    CODIGO, NOMBRE, PRESENTACION, REQUIERE_RECETA, STOCK_ACTUAL, STOCK_MINIMO, ESTADO
) VALUES (
    'MED-001', 'Amoxicilina', '500 mg capsulas', 'SI', 100, 10, 'ACTIVO'
);

INSERT INTO MEDICAMENTO (
    CODIGO, NOMBRE, PRESENTACION, REQUIERE_RECETA, STOCK_ACTUAL, STOCK_MINIMO, ESTADO
) VALUES (
    'MED-002', 'Ibuprofeno', '400 mg tabletas', 'NO', 200, 20, 'ACTIVO'
);

INSERT INTO MEDICAMENTO (
    CODIGO, NOMBRE, PRESENTACION, REQUIERE_RECETA, STOCK_ACTUAL, STOCK_MINIMO, ESTADO
) VALUES (
    'MED-003', 'Loratadina', '10 mg tabletas', 'NO', 150, 15, 'ACTIVO'
);

INSERT INTO MEDICAMENTO (
    CODIGO, NOMBRE, PRESENTACION, REQUIERE_RECETA, STOCK_ACTUAL, STOCK_MINIMO, ESTADO
) VALUES (
    'MED-004', 'Paracetamol', '500 mg tabletas', 'NO', 300, 30, 'ACTIVO'
);

INSERT INTO MEDICAMENTO (
    CODIGO, NOMBRE, PRESENTACION, REQUIERE_RECETA, STOCK_ACTUAL, STOCK_MINIMO, ESTADO
) VALUES (
    'MED-005', 'Azitromicina', '500 mg tabletas', 'SI', 80, 8, 'ACTIVO'
);


-- RECETAS
INSERT INTO RECETA (
    ID_PACIENTE, ID_MEDICO, FECHA_EMISION, ESTADO, OBSERVACIONES
) VALUES (
    1, 1, SYSDATE, 'ACTIVA', 'Paciente con tratamiento antibiotico'
);

INSERT INTO RECETA (
    ID_PACIENTE, ID_MEDICO, FECHA_EMISION, ESTADO, OBSERVACIONES
) VALUES (
    2, 2, SYSDATE, 'ACTIVA', 'Paciente con alergia estacional'
);


-- DETALLE DE RECETA
INSERT INTO RECETA_DETALLE (
    ID_RECETA, ID_MEDICAMENTO, DOSIS, CANTIDAD_AUTORIZADA, CANTIDAD_DISPENSADA, INDICACIONES
) VALUES (
    1, 1, '1 capsula cada 8 horas', 21, 0, 'Tomar por 7 dias'
);

INSERT INTO RECETA_DETALLE (
    ID_RECETA, ID_MEDICAMENTO, DOSIS, CANTIDAD_AUTORIZADA, CANTIDAD_DISPENSADA, INDICACIONES
) VALUES (
    1, 4, '1 tableta cada 6 horas', 12, 0, 'Tomar solo si hay dolor'
);

INSERT INTO RECETA_DETALLE (
    ID_RECETA, ID_MEDICAMENTO, DOSIS, CANTIDAD_AUTORIZADA, CANTIDAD_DISPENSADA, INDICACIONES
) VALUES (
    2, 3, '1 tableta diaria', 10, 0, 'Tomar por 10 dias'
);

COMMIT;