-- ============================================
-- FUNCIONES DEL PROYECTO FARMA-- Se utiliza Create or Replace en las funciones, para evitar usar drop, en caso de que alguna NO funcione o se corrija 
-- ============================================

-- 1. Obtener nombre completo de un usuario.
CREATE OR REPLACE FUNCTION FN_NOMBRE_COMPLETO_USUARIO (
    P_ID_USUARIO IN NUMBER
) RETURN VARCHAR2
IS
    V_NOMBRE VARCHAR2(200);
BEGIN
    SELECT NOMBRE || ' ' || APELLIDO1 || ' ' || NVL(APELLIDO2, '')
    INTO V_NOMBRE
    FROM USUARIO
    WHERE ID_USUARIO = P_ID_USUARIO;

    RETURN TRIM(V_NOMBRE);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'USUARIO NO ENCONTRADO';
END;
/

-- 2. Obtener nombre completo de un paciente.
CREATE OR REPLACE FUNCTION FN_NOMBRE_COMPLETO_PACIENTE (
    P_ID_PACIENTE IN NUMBER
) RETURN VARCHAR2
IS
    V_NOMBRE VARCHAR2(200);
BEGIN
    SELECT NOMBRE || ' ' || APELLIDO1 || ' ' || NVL(APELLIDO2, '')
    INTO V_NOMBRE
    FROM PACIENTE
    WHERE ID_PACIENTE = P_ID_PACIENTE;

    RETURN TRIM(V_NOMBRE);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'PACIENTE NO ENCONTRADO';
END;
/

-- 3. Obtener nombre completo de un medico.
CREATE OR REPLACE FUNCTION FN_NOMBRE_COMPLETO_MEDICO (
    P_ID_MEDICO IN NUMBER
) RETURN VARCHAR2
IS
    V_NOMBRE VARCHAR2(200);
BEGIN
    SELECT NOMBRE || ' ' || APELLIDO1 || ' ' || NVL(APELLIDO2, '')
    INTO V_NOMBRE
    FROM MEDICO
    WHERE ID_MEDICO = P_ID_MEDICO;

    RETURN TRIM(V_NOMBRE);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'MEDICO NO ENCONTRADO';
END;
/

-- 4. Obtener nombre de un medicamento.
CREATE OR REPLACE FUNCTION FN_NOMBRE_MEDICAMENTO (
    P_ID_MEDICAMENTO IN NUMBER
) RETURN VARCHAR2
IS
    V_NOMBRE VARCHAR2(100);
BEGIN
    SELECT NOMBRE
    INTO V_NOMBRE
    FROM MEDICAMENTO
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

    RETURN V_NOMBRE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'MEDICAMENTO NO ENCONTRADO';
END;
/

-- 5. Obtener stock actual de un medicamento.
CREATE OR REPLACE FUNCTION FN_STOCK_ACTUAL_MEDICAMENTO (
    P_ID_MEDICAMENTO IN NUMBER
) RETURN NUMBER
IS
    V_STOCK NUMBER;
BEGIN
    SELECT STOCK_ACTUAL
    INTO V_STOCK
    FROM MEDICAMENTO
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

    RETURN V_STOCK;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;
END;
/

-- 6. Obtener stock minimo de un medicamento.
CREATE OR REPLACE FUNCTION FN_STOCK_MINIMO_MEDICAMENTO (
    P_ID_MEDICAMENTO IN NUMBER
) RETURN NUMBER
IS
    V_STOCK NUMBER;
BEGIN
    SELECT STOCK_MINIMO
    INTO V_STOCK
    FROM MEDICAMENTO
    WHERE ID_MEDICAMENTO = P_ID_MEDICAMENTO;

    RETURN V_STOCK;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;
END;
/

-- 7. Validar si un paciente esta activo.
CREATE OR REPLACE FUNCTION FN_PACIENTE_ACTIVO (
    P_ID_PACIENTE IN NUMBER
) RETURN VARCHAR2
IS
    V_ESTADO VARCHAR2(15);
BEGIN
    SELECT ESTADO
    INTO V_ESTADO
    FROM PACIENTE
    WHERE ID_PACIENTE = P_ID_PACIENTE;

    RETURN V_ESTADO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'NO_EXISTE';
END;
/

-- 8. Validar si un medico esta activo.
CREATE OR REPLACE FUNCTION FN_MEDICO_ACTIVO (
    P_ID_MEDICO IN NUMBER
) RETURN VARCHAR2
IS
    V_ESTADO VARCHAR2(15);
BEGIN
    SELECT ESTADO
    INTO V_ESTADO
    FROM MEDICO
    WHERE ID_MEDICO = P_ID_MEDICO;

    RETURN V_ESTADO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'NO_EXISTE';
END;
/

-- 9. Validar si un usuario esta activo.
CREATE OR REPLACE FUNCTION FN_USUARIO_ACTIVO (
    P_ID_USUARIO IN NUMBER
) RETURN VARCHAR2
IS
    V_ESTADO VARCHAR2(15);
BEGIN
    SELECT ESTADO
    INTO V_ESTADO
    FROM USUARIO
    WHERE ID_USUARIO = P_ID_USUARIO;

    RETURN V_ESTADO;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'NO_EXISTE';
END;
/

-- 10. Obtener cantidad autorizada de un detalle de receta.
CREATE OR REPLACE FUNCTION FN_CANT_AUTORIZADA_RECETA (
    P_ID_RECETA_DETALLE IN NUMBER
) RETURN NUMBER
IS
    V_CANTIDAD NUMBER;
BEGIN
    SELECT CANTIDAD_AUTORIZADA
    INTO V_CANTIDAD
    FROM RECETA_DETALLE
    WHERE ID_RECETA_DETALLE = P_ID_RECETA_DETALLE;

    RETURN V_CANTIDAD;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;
END;
/

-- 11. Obtener cantidad dispensada de un detalle de receta.
CREATE OR REPLACE FUNCTION FN_CANT_DISPENSADA_RECETA (
    P_ID_RECETA_DETALLE IN NUMBER
) RETURN NUMBER
IS
    V_CANTIDAD NUMBER;
BEGIN
    SELECT CANTIDAD_DISPENSADA
    INTO V_CANTIDAD
    FROM RECETA_DETALLE
    WHERE ID_RECETA_DETALLE = P_ID_RECETA_DETALLE;

    RETURN V_CANTIDAD;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;
END;
/

-- 12. Obtener cantidad pendiente de un detalle de receta.
CREATE OR REPLACE FUNCTION FN_CANT_PENDIENTE_RECETA (
    P_ID_RECETA_DETALLE IN NUMBER
) RETURN NUMBER
IS
    V_AUT NUMBER;
    V_DISP NUMBER;
BEGIN
    SELECT CANTIDAD_AUTORIZADA, CANTIDAD_DISPENSADA
    INTO V_AUT, V_DISP
    FROM RECETA_DETALLE
    WHERE ID_RECETA_DETALLE = P_ID_RECETA_DETALLE;

    RETURN V_AUT - V_DISP;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;
END;
/

-- 13. Contar detalles pendientes de una receta.
CREATE OR REPLACE FUNCTION FN_TOTAL_DETALLES_PENDIENTES (
    P_ID_RECETA IN NUMBER
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM RECETA_DETALLE
    WHERE ID_RECETA = P_ID_RECETA
      AND CANTIDAD_DISPENSADA < CANTIDAD_AUTORIZADA;

    RETURN V_TOTAL;
END;
/

-- 14. Validar si una receta esta completa.
CREATE OR REPLACE FUNCTION FN_RECETA_COMPLETA (
    P_ID_RECETA IN NUMBER
) RETURN VARCHAR2
IS
    V_PENDIENTES NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_PENDIENTES
    FROM RECETA_DETALLE
    WHERE ID_RECETA = P_ID_RECETA
      AND CANTIDAD_DISPENSADA < CANTIDAD_AUTORIZADA;

    IF V_PENDIENTES = 0 THEN
        RETURN 'SI';
    ELSE
        RETURN 'NO';
    END IF;
END;
/

-- 15. Obtener total dispensado en una dispensacion.
CREATE OR REPLACE FUNCTION FN_TOTAL_DISPENSADO (
    P_ID_DISPENSACION IN NUMBER
) RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT NVL(SUM(CANTIDAD_DISPENSADA), 0)
    INTO V_TOTAL
    FROM DISPENSACION_DETALLE
    WHERE ID_DISPENSACION = P_ID_DISPENSACION;

    RETURN V_TOTAL;
END;
/